// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Attendance struct {
	ID           int64        `json:"id"`
	DiscordUser  string       `json:"discord_user"`
	CheckpointID int64        `json:"checkpoint_id"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type Checkpoint struct {
	ID          int64        `json:"id"`
	ScheduledAt string       `json:"scheduled_at"`
	ChannelID   string       `json:"channel_id"`
	GuildID     string       `json:"guild_id"`
	DiscordUser string       `json:"discord_user"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type CheckpointRsvp struct {
	ID           int64        `json:"id"`
	CheckpointID int64        `json:"checkpoint_id"`
	DiscordUser  string       `json:"discord_user"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type DiscordUser struct {
	DiscordUser string `json:"discord_user"`
}

type Goal struct {
	ID           int64        `json:"id"`
	DiscordUser  string       `json:"discord_user"`
	Description  string       `json:"description"`
	CheckpointID int64        `json:"checkpoint_id"`
	Status       string       `json:"status"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type Guild struct {
	GuildID   string       `json:"guild_id"`
	Timezone  string       `json:"timezone"`
	OwnerID   string       `json:"owner_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}
