// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"
)

const completeGoal = `-- name: CompleteGoal :exec
UPDATE goals
SET status = 'completed'
WHERE discord_user = ? AND checkpoint_id = ?
`

type CompleteGoalParams struct {
	DiscordUser  string `json:"discord_user"`
	CheckpointID int64  `json:"checkpoint_id"`
}

func (q *Queries) CompleteGoal(ctx context.Context, arg CompleteGoalParams) error {
	_, err := q.db.ExecContext(ctx, completeGoal, arg.DiscordUser, arg.CheckpointID)
	return err
}

const createCheckpoint = `-- name: CreateCheckpoint :one
/*
  File Conventions:
    - All Create operations return the created record
*/

INSERT INTO checkpoints (scheduled_at, channel_id, guild_id, discord_user)
VALUES (?, ?, ?, ?) RETURNING id, scheduled_at, channel_id, guild_id, discord_user, created_at
`

type CreateCheckpointParams struct {
	ScheduledAt string `json:"scheduled_at"`
	ChannelID   string `json:"channel_id"`
	GuildID     string `json:"guild_id"`
	DiscordUser string `json:"discord_user"`
}

func (q *Queries) CreateCheckpoint(ctx context.Context, arg CreateCheckpointParams) (Checkpoint, error) {
	row := q.db.QueryRowContext(ctx, createCheckpoint,
		arg.ScheduledAt,
		arg.ChannelID,
		arg.GuildID,
		arg.DiscordUser,
	)
	var i Checkpoint
	err := row.Scan(
		&i.ID,
		&i.ScheduledAt,
		&i.ChannelID,
		&i.GuildID,
		&i.DiscordUser,
		&i.CreatedAt,
	)
	return i, err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (discord_user, description, checkpoint_id)
VALUES (?, ?, ?) RETURNING id, discord_user, description, checkpoint_id, status, created_at
`

type CreateGoalParams struct {
	DiscordUser  string `json:"discord_user"`
	Description  string `json:"description"`
	CheckpointID int64  `json:"checkpoint_id"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, createGoal, arg.DiscordUser, arg.Description, arg.CheckpointID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.DiscordUser,
		&i.Description,
		&i.CheckpointID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createGuild = `-- name: CreateGuild :one
INSERT INTO guilds (guild_id, timezone, owner_id)
VALUES (?, ?, ?) RETURNING guild_id, timezone, owner_id, created_at
`

type CreateGuildParams struct {
	GuildID  string `json:"guild_id"`
	Timezone string `json:"timezone"`
	OwnerID  string `json:"owner_id"`
}

func (q *Queries) CreateGuild(ctx context.Context, arg CreateGuildParams) (Guild, error) {
	row := q.db.QueryRowContext(ctx, createGuild, arg.GuildID, arg.Timezone, arg.OwnerID)
	var i Guild
	err := row.Scan(
		&i.GuildID,
		&i.Timezone,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const failedGoal = `-- name: FailedGoal :exec
UPDATE goals
SET status = 'failed'
WHERE discord_user = ? AND checkpoint_id = ?
`

type FailedGoalParams struct {
	DiscordUser  string `json:"discord_user"`
	CheckpointID int64  `json:"checkpoint_id"`
}

func (q *Queries) FailedGoal(ctx context.Context, arg FailedGoalParams) error {
	_, err := q.db.ExecContext(ctx, failedGoal, arg.DiscordUser, arg.CheckpointID)
	return err
}

const getCheckpointByScheduledAtAndChannel = `-- name: GetCheckpointByScheduledAtAndChannel :one
SELECT id, scheduled_at, channel_id, guild_id, discord_user, created_at FROM checkpoints
WHERE scheduled_at = ? AND channel_id = ?
`

type GetCheckpointByScheduledAtAndChannelParams struct {
	ScheduledAt string `json:"scheduled_at"`
	ChannelID   string `json:"channel_id"`
}

func (q *Queries) GetCheckpointByScheduledAtAndChannel(ctx context.Context, arg GetCheckpointByScheduledAtAndChannelParams) (Checkpoint, error) {
	row := q.db.QueryRowContext(ctx, getCheckpointByScheduledAtAndChannel, arg.ScheduledAt, arg.ChannelID)
	var i Checkpoint
	err := row.Scan(
		&i.ID,
		&i.ScheduledAt,
		&i.ChannelID,
		&i.GuildID,
		&i.DiscordUser,
		&i.CreatedAt,
	)
	return i, err
}

const getGuild = `-- name: GetGuild :one
SELECT guild_id, timezone, owner_id, created_at FROM guilds
WHERE guild_id = ?
`

func (q *Queries) GetGuild(ctx context.Context, guildID string) (Guild, error) {
	row := q.db.QueryRowContext(ctx, getGuild, guildID)
	var i Guild
	err := row.Scan(
		&i.GuildID,
		&i.Timezone,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getPastCheckpointsByChannel = `-- name: GetPastCheckpointsByChannel :many
SELECT id, scheduled_at, channel_id, guild_id, discord_user, created_at FROM checkpoints
WHERE channel_id = ? AND datetime(scheduled_at) < datetime('now')
ORDER BY datetime(scheduled_at) DESC
`

func (q *Queries) GetPastCheckpointsByChannel(ctx context.Context, channelID string) ([]Checkpoint, error) {
	rows, err := q.db.QueryContext(ctx, getPastCheckpointsByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Checkpoint
	for rows.Next() {
		var i Checkpoint
		if err := rows.Scan(
			&i.ID,
			&i.ScheduledAt,
			&i.ChannelID,
			&i.GuildID,
			&i.DiscordUser,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingCheckpointByGuildAndChannel = `-- name: GetUpcomingCheckpointByGuildAndChannel :one
SELECT id, scheduled_at, channel_id, guild_id, discord_user, created_at FROM checkpoints
WHERE guild_id = ? AND channel_id = ? AND datetime(scheduled_at) >= datetime('now')
ORDER BY datetime(scheduled_at) ASC
LIMIT 1
`

type GetUpcomingCheckpointByGuildAndChannelParams struct {
	GuildID   string `json:"guild_id"`
	ChannelID string `json:"channel_id"`
}

func (q *Queries) GetUpcomingCheckpointByGuildAndChannel(ctx context.Context, arg GetUpcomingCheckpointByGuildAndChannelParams) (Checkpoint, error) {
	row := q.db.QueryRowContext(ctx, getUpcomingCheckpointByGuildAndChannel, arg.GuildID, arg.ChannelID)
	var i Checkpoint
	err := row.Scan(
		&i.ID,
		&i.ScheduledAt,
		&i.ChannelID,
		&i.GuildID,
		&i.DiscordUser,
		&i.CreatedAt,
	)
	return i, err
}

const getUpcomingCheckpoints = `-- name: GetUpcomingCheckpoints :many
SELECT id, scheduled_at, channel_id, guild_id, discord_user, created_at FROM checkpoints
WHERE datetime(scheduled_at) >= datetime('now')
ORDER BY datetime(scheduled_at) ASC
`

func (q *Queries) GetUpcomingCheckpoints(ctx context.Context) ([]Checkpoint, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingCheckpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Checkpoint
	for rows.Next() {
		var i Checkpoint
		if err := rows.Scan(
			&i.ID,
			&i.ScheduledAt,
			&i.ChannelID,
			&i.GuildID,
			&i.DiscordUser,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttendance = `-- name: MarkAttendance :exec
INSERT OR IGNORE INTO attendance (discord_user, checkpoint_id)
VALUES (?, ?)
`

type MarkAttendanceParams struct {
	DiscordUser  string `json:"discord_user"`
	CheckpointID int64  `json:"checkpoint_id"`
}

func (q *Queries) MarkAttendance(ctx context.Context, arg MarkAttendanceParams) error {
	_, err := q.db.ExecContext(ctx, markAttendance, arg.DiscordUser, arg.CheckpointID)
	return err
}
