// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Attendance struct {
	ID           int64
	DiscordUser  string
	CheckpointID int64
	CreatedAt    sql.NullTime
}

type Checkpoint struct {
	ID          int64
	ScheduledAt string
	ChannelID   string
	CreatedAt   sql.NullTime
}

type Goal struct {
	ID           int64
	DiscordUser  string
	Description  string
	CheckpointID int64
	Status       string
	CreatedAt    sql.NullTime
}
