package database

import (
	"context"
	"database/sql"

	"github.com/charmbracelet/log"
	"github.com/metruzanca/checkpoint-bot/bot/db"
	_ "modernc.org/sqlite"
)

// Compile time check to ensure SQLiteCheckpointDatabase implements CheckpointDatabase
var _ CheckpointDatabase = (*SQLiteCheckpointDatabase)(nil)

type SQLiteCheckpointDatabase struct {
	// queries generated by sqlc
	queries *db.Queries
	// connection instance
	db *sql.DB
}

func NewSQLiteCheckpointDatabase() *SQLiteCheckpointDatabase {

	// ctx := context.Background()

	sqliteDB, err := sql.Open("sqlite", ":memory:")
	if err != nil {
		log.Fatal("Error opening SQLite database: ", "err", err)
	}

	return &SQLiteCheckpointDatabase{
		queries: db.New(sqliteDB),
		db:      sqliteDB,
	}
}

// Implementations for CheckpointDatabase interface

func (db *SQLiteCheckpointDatabase) CreateCheckpoint(ctx context.Context, params db.CreateCheckpointParams) (*db.Checkpoint, error) {
	record, err := db.queries.CreateCheckpoint(ctx, params)
	if err != nil {
		return nil, err
	}
	return &record, nil
}

func (db *SQLiteCheckpointDatabase) GetUpcomingCheckpoint(ctx context.Context) (*db.Checkpoint, error) {
	record, err := db.queries.GetUpcomingCheckpoint(ctx)
	if err != nil {
		return nil, err
	}
	return &record, nil
}
