package database

import (
	"context"
	"database/sql"

	"github.com/charmbracelet/log"
	"github.com/metruzanca/checkpoint-bot/internal/migrations"
	"github.com/metruzanca/checkpoint-bot/internal/sqlc"
	_ "modernc.org/sqlite"
)

// Compile time check to ensure SQLiteCheckpointDatabase implements CheckpointDatabase
var _ CheckpointDatabase = (*SQLiteCheckpointDatabase)(nil)

type SQLiteCheckpointDatabase struct {
	// queries generated by sqlc
	queries *sqlc.Queries
	// connection instance
	db *sql.DB
}

func NewSQLiteCheckpointDatabase(dbPath string) *SQLiteCheckpointDatabase {
	if dbPath == "" {
		dbPath = "checkpoint.db"
	}

	sqliteDB, err := sql.Open("sqlite", dbPath)
	if err != nil {
		log.Fatal("Error opening SQLite database", "err", err, "path", dbPath)
	}

	// Run migrations on startup (includes PRAGMA foreign_keys = ON)
	if err := migrations.Up(sqliteDB); err != nil {
		log.Fatal("Error running migrations", "err", err)
	}

	return &SQLiteCheckpointDatabase{
		queries: sqlc.New(sqliteDB),
		db:      sqliteDB,
	}
}

// Implementations for CheckpointDatabase interface

func (db *SQLiteCheckpointDatabase) CreateCheckpoint(ctx context.Context, params sqlc.CreateCheckpointParams) (*sqlc.Checkpoint, error) {
	record, err := db.queries.CreateCheckpoint(ctx, params)
	if err != nil {
		return nil, err
	}

	log.Info("Created checkpoint", "checkpoint", record)

	return &record, nil
}

func (db *SQLiteCheckpointDatabase) GetUpcomingCheckpoint(ctx context.Context) (*sqlc.Checkpoint, error) {
	record, err := db.queries.GetUpcomingCheckpoint(ctx)
	if err != nil {
		return nil, err
	}
	return &record, nil
}
