package sqlite

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"os"
	"path/filepath"

	"github.com/charmbracelet/log"
	"github.com/metruzanca/checkpoint-bot/internal/database"
	"github.com/metruzanca/checkpoint-bot/internal/database/migrations"
	"github.com/metruzanca/checkpoint-bot/internal/database/queries"
	sqlite "modernc.org/sqlite"
)

// Compile time check to ensure SQLiteCheckpointDatabase implements CheckpointDatabase
var _ database.CheckpointDatabase = (*SqliteDatabase)(nil)

type SqliteDatabase struct {
	// queries generated by sqlc
	queries *queries.Queries
	// connection instance
	db *sql.DB
}

func NewSqliteDatabase(dbPath string) *SqliteDatabase {
	if err := os.MkdirAll(filepath.Dir(dbPath), 0755); err != nil {
		log.Fatal("Error creating database directory", "err", err)
	}

	// foreign_keys needs to be set on each connection
	sqlite.RegisterConnectionHook(func(conn sqlite.ExecQuerierContext, dsn string) error {
		ctx := context.Background()
		// Set connection-specific PRAGMA statements
		if _, err := conn.ExecContext(ctx, "PRAGMA foreign_keys = ON;", []driver.NamedValue{}); err != nil {
			return err
		}

		return nil
	})

	sqliteDB, err := sql.Open("sqlite", dbPath)
	if err != nil {
		log.Fatal("Error opening SQLite database", "err", err, "path", dbPath)
	}

	// Configure connection pool for SQLite
	// With WAL mode enabled, SQLite can handle multiple concurrent readers
	sqliteDB.SetMaxOpenConns(10)
	sqliteDB.SetMaxIdleConns(2)

	// Set WAL mode on the database file (persists across connections)
	// This must be set outside of transactions (goose runs migrations in transactions)
	if _, err := sqliteDB.Exec("PRAGMA journal_mode=WAL;"); err != nil {
		log.Fatal("Error setting journal_mode", "err", err)
	}

	// Run migrations on startup
	if err := migrations.Up(sqliteDB); err != nil {
		log.Fatal("Error running migrations", "err", err)
	}

	return &SqliteDatabase{
		queries: queries.New(sqliteDB),
		db:      sqliteDB,
	}
}
